# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idaddress', models.CharField(max_length=20)),
                ('vm_type', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('cpu', models.IntegerField()),
            ],
        ),
    ]
