# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='cpu',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='mem',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
