# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20170420_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='idaddress',
            new_name='ipaddress',
        ),
    ]
